In [42]:
import pandas as pd
from wits_consumer import WitsConsumer

In [43]:
# # Necessary in case your production file does not match with current list of country/code
# https://comtrade.un.org/Data/cache/reporterAreas.json

# wc = WitsConsumer()
# country_codes = wc.get_list_iso3codes()
# country_codes

## Now HHI for production

In [147]:
df_production = pd.read_csv("../../data/Production/Production_one_file_2.csv")

In [148]:
# df_production["Country"] = df_production["Country"].str.upper()
# df_production["Product"] = df_production["Product"].str.upper()
df_production["Year"] = df_production["Year"].apply(int).apply(str)
df_production

,Country,Product,cmdCode,Source,Year,Value,Value (Ton),qtyUnitAbbr,reporterCode
0,ALBANIA,IRON ORE (FE-CONT.),2601.0,org,1984,4.395020e+08,439502.0,kg,8.0
1,ALGERIA,IRON ORE (FE-CONT.),2601.0,org,1984,2.000000e+09,2000000.0,kg,12.0
2,ARGENTINA,IRON ORE (FE-CONT.),2601.0,org,1984,3.455760e+08,345576.0,kg,32.0
3,AUSTRALIA,IRON ORE (FE-CONT.),2601.0,org,1984,5.688500e+10,56885000.0,kg,36.0
4,AUSTRIA,IRON ORE (FE-CONT.),2601.0,org,1984,1.137872e+09,1137872.0,kg,40.0
...,...,...,...,...,...,...,...,...,...
96380,SPAIN,URANIUM (U3O8-CONT.),261210.0,org,2020,NaN,NaN,kg,724.0
96381,UKRAINE,URANIUM (U3O8-CONT.),261210.0,org,2020,8.770000e+05,877.0,kg,804.0
96382,UNITED STATES,URANIUM (U3O8-CONT.),261210.0,org,2020,7.000000e+03,7.0,kg,842.0
96383,UZBEKISTAN,URANIUM (U3O8-CONT.),261210.0,org,2020,4.127000e+06,4127.0,kg,860.0
96384,YUGOSLAVIA,URANIUM (U3O8-CONT.),261210.0,org,2020,NaN,NaN,kg,890.0

In [46]:
df_production["Product"].unique()

array(['IRON ORE (FE-CONT.)', 'CHROMIUM (CR2O3-CONT.)', 'COBALT',
       'MANGANESE (MN-CONT.)', 'MOLYBDENUM', 'NICKEL',
       'NIOBIUM (NB2O5-CONT.)', 'TANTALUM (TA2O5-CONT.)',
       'TITANIUM (TIO2-CONT.)', 'TUNGSTEN (W-CONT.)',
       'VANADIUM (V-CONT.)', 'ALUMINIUM', 'ANTIMONY',
       'ARSENIC (AS2O3-CONT.)', 'BAUXITE (CRUDE)', 'BERYLLIUM (CONC.)',
       'BISMUTH', 'CADMIUM', 'COPPER', 'GALLIUM', 'GERMANIUM', 'INDIUM',
       'LEAD', 'LITHIUM (LI2O-CONT.)', 'LITHIUM (USGS)', 'MERCURY',
       'RARE EARTHS (REO-CONT.)', 'RHENIUM (KG)', 'SELENIUM', 'TELLURIUM',
       'TIN', 'ZINC', 'GOLD (KG)', 'PALLADIUM (KG)', 'PLATINUM (KG)',
       'RHODIUM (KG)', 'SILVER (KG)', 'TAJIKISTAN', 'ASBESTOS', 'BARYTE',
       'BENTONITE', 'BORON', 'DIAM. (GEM) CT', 'DIAM. (IND) CT',
       'DIATOMITE', 'FELDSPAR', 'FLUORSPAR', 'GRAPHITE',
       'GYPSUM AND ANHYDRITE', 'KAOLIN', 'MAGNESITE', 'PERLITE',
       'PHOSPHATES (P2O5-CONT.)', 'POTASH (K2O-CONT.)', 'SALT', 'SULFUR',
       'TALC', 'VERMICULITE', 'ZIRCON (CONC.)', 'STEAM COAL',
       'COKING COAL', 'LIGNITE', 'NATURAL GAS (MIO. M3, MARKETED)',
       'PETROLEUM (INCL. NGLS, GROSS)',
       'OIL SANDS (PART OF PETROLEUM, GROSS)', 'OIL SHALES',
       'URANIUM (U3O8-CONT.)'], dtype=object)

In [47]:
df_production[(df_production["Product"] == "MANGANESE (MN-CONT.)") & (df_production["Country"] == "CANADA")]

Empty DataFrame
Columns: [Country, Product, cmdCode, Source, Year, Value, Value (Ton), qtyUnitAbbr, reporterCode]
Index: []

In [149]:
df_production_summarized = df_production.groupby(["Year", "Product"])[["Value"]].sum().reset_index()
df_production_summarized.rename(columns={"Value": "Total_value_YearProduct"}, inplace=True)
df_production_summarized

      Year                Product  Total_value_YearProduct
0     1984              ALUMINIUM             1.684394e+10
1     1984               ANTIMONY             5.773100e+07
2     1984  ARSENIC (AS2O3-CONT.)             3.869100e+07
3     1984               ASBESTOS             4.268221e+09
4     1984                 BARYTE             7.313479e+09
...    ...                    ...                      ...
2474  2020   URANIUM (U3O8-CONT.)             5.626900e+07
2475  2020     VANADIUM (V-CONT.)             1.057760e+08
2476  2020            VERMICULITE             4.166380e+08
2477  2020                   ZINC             1.260830e+10
2478  2020         ZIRCON (CONC.)             1.235632e+09

[2479 rows x 3 columns]

### Let's left-join production and total value of production by (Year, Product)

In [150]:
df = pd.merge(df_production, df_production_summarized, how="left", left_on=["Year", "Product"], right_on=["Year", "Product"])
df

,Country,Product,cmdCode,Source,Year,Value,Value (Ton),qtyUnitAbbr,reporterCode,Total_value_YearProduct
0,ALBANIA,IRON ORE (FE-CONT.),2601.0,org,1984,4.395020e+08,439502.0,kg,8.0,4.468878e+11
1,ALGERIA,IRON ORE (FE-CONT.),2601.0,org,1984,2.000000e+09,2000000.0,kg,12.0,4.468878e+11
2,ARGENTINA,IRON ORE (FE-CONT.),2601.0,org,1984,3.455760e+08,345576.0,kg,32.0,4.468878e+11
3,AUSTRALIA,IRON ORE (FE-CONT.),2601.0,org,1984,5.688500e+10,56885000.0,kg,36.0,4.468878e+11
4,AUSTRIA,IRON ORE (FE-CONT.),2601.0,org,1984,1.137872e+09,1137872.0,kg,40.0,4.468878e+11
...,...,...,...,...,...,...,...,...,...,...
96380,SPAIN,URANIUM (U3O8-CONT.),261210.0,org,2020,NaN,NaN,kg,724.0,5.626900e+07
96381,UKRAINE,URANIUM (U3O8-CONT.),261210.0,org,2020,8.770000e+05,877.0,kg,804.0,5.626900e+07
96382,UNITED STATES,URANIUM (U3O8-CONT.),261210.0,org,2020,7.000000e+03,7.0,kg,842.0,5.626900e+07
96383,UZBEKISTAN,URANIUM (U3O8-CONT.),261210.0,org,2020,4.127000e+06,4127.0,kg,860.0,5.626900e+07
96384,YUGOSLAVIA,URANIUM (U3O8-CONT.),261210.0,org,2020,NaN,NaN,kg,890.0,5.626900e+07

In [151]:
# df["Share in %"] = df["Value"] * 100 / df["Total_value_YearProduct"]
df["Share in %"] = df["Value"] * 1 / df["Total_value_YearProduct"]
df["Share HHI Production"] = df["Share in %"] ** 2
df

,Country,Product,cmdCode,Source,Year,Value,Value (Ton),qtyUnitAbbr,reporterCode,Total_value_YearProduct,Share in %,Share HHI Production
0,ALBANIA,IRON ORE (FE-CONT.),2601.0,org,1984,4.395020e+08,439502.0,kg,8.0,4.468878e+11,0.000983,9.672186e-07
1,ALGERIA,IRON ORE (FE-CONT.),2601.0,org,1984,2.000000e+09,2000000.0,kg,12.0,4.468878e+11,0.004475,2.002917e-05
2,ARGENTINA,IRON ORE (FE-CONT.),2601.0,org,1984,3.455760e+08,345576.0,kg,32.0,4.468878e+11,0.000773,5.979847e-07
3,AUSTRALIA,IRON ORE (FE-CONT.),2601.0,org,1984,5.688500e+10,56885000.0,kg,36.0,4.468878e+11,0.127291,1.620311e-02
4,AUSTRIA,IRON ORE (FE-CONT.),2601.0,org,1984,1.137872e+09,1137872.0,kg,40.0,4.468878e+11,0.002546,6.483205e-06
...,...,...,...,...,...,...,...,...,...,...,...,...
96380,SPAIN,URANIUM (U3O8-CONT.),261210.0,org,2020,NaN,NaN,kg,724.0,5.626900e+07,NaN,NaN
96381,UKRAINE,URANIUM (U3O8-CONT.),261210.0,org,2020,8.770000e+05,877.0,kg,804.0,5.626900e+07,0.015586,2.429186e-04
96382,UNITED STATES,URANIUM (U3O8-CONT.),261210.0,org,2020,7.000000e+03,7.0,kg,842.0,5.626900e+07,0.000124,1.547596e-08
96383,UZBEKISTAN,URANIUM (U3O8-CONT.),261210.0,org,2020,4.127000e+06,4127.0,kg,860.0,5.626900e+07,0.073344,5.379359e-03
96384,YUGOSLAVIA,URANIUM (U3O8-CONT.),261210.0,org,2020,NaN,NaN,kg,890.0,5.626900e+07,NaN,NaN

### Sum the "Share HHI Production" by (Year, Product) and you get the HHI index :)

In [152]:
df_hhi_production = df.groupby(["Year", "Product"])[["Share HHI Production"]].sum().reset_index()
df_hhi_production.rename(columns={"Share HHI Production": "HHI_production"}, inplace=True)
df_hhi_production = pd.merge(df, df_hhi_production, how="left", left_on=["Year", "Product"], right_on=["Year", "Product"])
df_hhi_production
# CONSIDERATIONS
# - Currently the HHI value is pasted to the row even if the production is null. Shall we replace by NANs if production is null?

,Country,Product,cmdCode,Source,Year,Value,Value (Ton),qtyUnitAbbr,reporterCode,Total_value_YearProduct,Share in %,Share HHI Production,HHI_production
0,ALBANIA,IRON ORE (FE-CONT.),2601.0,org,1984,4.395020e+08,439502.0,kg,8.0,4.468878e+11,0.000983,9.672186e-07,0.151834
1,ALGERIA,IRON ORE (FE-CONT.),2601.0,org,1984,2.000000e+09,2000000.0,kg,12.0,4.468878e+11,0.004475,2.002917e-05,0.151834
2,ARGENTINA,IRON ORE (FE-CONT.),2601.0,org,1984,3.455760e+08,345576.0,kg,32.0,4.468878e+11,0.000773,5.979847e-07,0.151834
3,AUSTRALIA,IRON ORE (FE-CONT.),2601.0,org,1984,5.688500e+10,56885000.0,kg,36.0,4.468878e+11,0.127291,1.620311e-02,0.151834
4,AUSTRIA,IRON ORE (FE-CONT.),2601.0,org,1984,1.137872e+09,1137872.0,kg,40.0,4.468878e+11,0.002546,6.483205e-06,0.151834
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96380,SPAIN,URANIUM (U3O8-CONT.),261210.0,org,2020,NaN,NaN,kg,724.0,5.626900e+07,NaN,NaN,0.218243
96381,UKRAINE,URANIUM (U3O8-CONT.),261210.0,org,2020,8.770000e+05,877.0,kg,804.0,5.626900e+07,0.015586,2.429186e-04,0.218243
96382,UNITED STATES,URANIUM (U3O8-CONT.),261210.0,org,2020,7.000000e+03,7.0,kg,842.0,5.626900e+07,0.000124,1.547596e-08,0.218243
96383,UZBEKISTAN,URANIUM (U3O8-CONT.),261210.0,org,2020,4.127000e+06,4127.0,kg,860.0,5.626900e+07,0.073344,5.379359e-03,0.218243
96384,YUGOSLAVIA,URANIUM (U3O8-CONT.),261210.0,org,2020,NaN,NaN,kg,890.0,5.626900e+07,NaN,NaN,0.218243

In [154]:
df_hhi_production = df_hhi_production[["Product", "cmdCode", "Year", "qtyUnitAbbr", "Source", "HHI_production"]].drop_duplicates(subset=["Product", "cmdCode", "Year", "qtyUnitAbbr", "Source"]).reset_index(drop=True)
df_hhi_production

                   Product   cmdCode  Year qtyUnitAbbr Source  HHI_production
0      IRON ORE (FE-CONT.)    2601.0  1984          kg    org        0.151834
1      IRON ORE (FE-CONT.)    2601.0  1985          kg    org        0.138131
2      IRON ORE (FE-CONT.)    2601.0  1986          kg    org        0.137646
3      IRON ORE (FE-CONT.)    2601.0  1987          kg    org        0.138844
4      IRON ORE (FE-CONT.)    2601.0  1988          kg    org        0.137387
...                    ...       ...   ...         ...    ...             ...
2474  URANIUM (U3O8-CONT.)  261210.0  2016          kg    org        0.224366
2475  URANIUM (U3O8-CONT.)  261210.0  2017          kg    org        0.219018
2476  URANIUM (U3O8-CONT.)  261210.0  2018          kg    org        0.212503
2477  URANIUM (U3O8-CONT.)  261210.0  2019          kg    org        0.227431
2478  URANIUM (U3O8-CONT.)  261210.0  2020          kg    org        0.218243

[2479 rows x 6 columns]

In [ ]:
df_hhi_production

### NEW: Scale HHI_Production between [0,1]

In [74]:
# df_hhi_production[(df_hhi_production["Country"] == "CANADA") & (df_hhi_production["Product"] == "OIL SANDS (PART OF PETROLEUM, GROSS)")]

In [155]:
# max_value is 10,000 and is canada for selenium. It's the only one country that produces seleniun
max_hhi = df_hhi_production["HHI_production"].max()
min_hhi = df_hhi_production["HHI_production"].min()
df_hhi_production["HHI_production_scaled"] = (df_hhi_production["HHI_production"] - min_hhi) / (max_hhi - min_hhi)
df_hhi_production

,Product,cmdCode,Year,qtyUnitAbbr,Source,HHI_production,HHI_production_scaled
0,IRON ORE (FE-CONT.),2601.0,1984,kg,org,0.151834,0.151834
1,IRON ORE (FE-CONT.),2601.0,1985,kg,org,0.138131,0.138131
2,IRON ORE (FE-CONT.),2601.0,1986,kg,org,0.137646,0.137646
3,IRON ORE (FE-CONT.),2601.0,1987,kg,org,0.138844,0.138844
4,IRON ORE (FE-CONT.),2601.0,1988,kg,org,0.137387,0.137387
...,...,...,...,...,...,...,...
2474,URANIUM (U3O8-CONT.),261210.0,2016,kg,org,0.224366,0.224366
2475,URANIUM (U3O8-CONT.),261210.0,2017,kg,org,0.219018,0.219018
2476,URANIUM (U3O8-CONT.),261210.0,2018,kg,org,0.212503,0.212503
2477,URANIUM (U3O8-CONT.),261210.0,2019,kg,org,0.227431,0.227431
2478,URANIUM (U3O8-CONT.),261210.0,2020,kg,org,0.218243,0.218243

In [156]:
df_hhi_production.to_csv("../../data/hhi_data/df_hhi_production.csv", index=False)

### Now only consider entries where year >= 2000

In [157]:
# Remove all the rows where year < 2000
df_hhi_production_2000s =df_hhi_production[df_hhi_production["Year"].apply(int) >= 2000]

In [158]:
# max_value is 10,000 and is canada for selenium. It's the only one country that produces seleniun
max_hhi = df_hhi_production_2000s["HHI_production"].max()
min_hhi = df_hhi_production_2000s["HHI_production"].min()
df_hhi_production_2000s["HHI_production_scaled"] = (df_hhi_production_2000s["HHI_production"] - min_hhi) / (max_hhi - min_hhi)
df_hhi_production_2000s

c:\Users\zacat\OneDrive\Documentos\Investigacion\investigacion-gnn-cic\rb_venv3715\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,Product,cmdCode,Year,qtyUnitAbbr,Source,HHI_production,HHI_production_scaled
16,IRON ORE (FE-CONT.),2601.0,2000,kg,org,0.120238,0.075656
17,IRON ORE (FE-CONT.),2601.0,2001,kg,org,0.127200,0.083260
18,IRON ORE (FE-CONT.),2601.0,2002,kg,org,0.124491,0.080301
19,IRON ORE (FE-CONT.),2601.0,2003,kg,org,0.127726,0.083835
20,IRON ORE (FE-CONT.),2601.0,2004,kg,org,0.132830,0.089409
...,...,...,...,...,...,...,...
2474,URANIUM (U3O8-CONT.),261210.0,2016,kg,org,0.224366,0.189390
2475,URANIUM (U3O8-CONT.),261210.0,2017,kg,org,0.219018,0.183548
2476,URANIUM (U3O8-CONT.),261210.0,2018,kg,org,0.212503,0.176431
2477,URANIUM (U3O8-CONT.),261210.0,2019,kg,org,0.227431,0.192737
2478,URANIUM (U3O8-CONT.),261210.0,2020,kg,org,0.218243,0.182702

In [159]:
df_hhi_production_2000s[df_hhi_production_2000s["HHI_production"] == df_hhi_production_2000s["HHI_production"].max()]

,Product,cmdCode,Year,qtyUnitAbbr,Source,HHI_production,HHI_production_scaled
987,RARE EARTHS (REO-CONT.),2846.0,2009,kg,org,0.966515,1.0

In [87]:
df_hhi_production_2000s[df_hhi_production_2000s["HHI_production"] == df_hhi_production_2000s["HHI_production"].min()]

        Product  cmdCode  Year  HHI_production  HHI_production_scaled
1218  GOLD (KG)   7108.0  2018        0.050972                    0.0

In [160]:
df_hhi_production_2000s.to_csv("../../data/hhi_data/df_hhi_production_2000.csv", index=False)

## Now HHI for exports

In [161]:
df_exports = pd.read_csv("../../data/exports/exports_consolidated_file.csv")
df_exports.rename(columns={"period": "Year"}, inplace=True)
df_exports

,typeCode,freqCode,refPeriodId,refYear,refMonth,Year,reporterCode,reporterISO,reporterDesc,flowCode,flowDesc,partnerCode,partnerISO,partnerDesc,partner2Code,partner2ISO,partner2Desc,classificationCode,classificationSearchCode,isOriginalClassification,cmdCode,cmdDesc,aggrLevel,isLeaf,customsCode,customsDesc,mosCode,motCode,motDesc,qtyUnitCode,qtyUnitAbbr,qty,isQtyEstimated,altQtyUnitCode,altQtyUnitAbbr,altQty,isAltQtyEstimated,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate,Product
0,C,A,20000101,2000,52,2000,32,ARG,Argentina,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,14000.0,False,-1,NaN,NaN,False,1.400000e+04,False,NaN,False,NaN,4.291000e+03,4.291000e+03,0,False,False,ALUMINIUM
1,C,A,20000101,2000,52,2000,40,AUT,Austria,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,128800.0,False,-1,NaN,NaN,False,1.288000e+05,False,NaN,False,NaN,2.275000e+04,2.275000e+04,0,False,False,ALUMINIUM
2,C,A,20000101,2000,52,2000,56,BEL,Belgium,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,133826657.0,False,-1,NaN,NaN,False,1.338267e+08,False,NaN,False,NaN,1.435771e+07,1.435771e+07,0,False,False,ALUMINIUM
3,C,A,20000101,2000,52,2000,76,BRA,Brazil,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,5135286.0,False,8,kg,5135286.0,False,4.166202e+09,False,0.0,False,0.0,1.131292e+08,1.131292e+08,0,False,True,ALUMINIUM
4,C,A,20000101,2000,52,2000,100,BGR,Bulgaria,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,920981.0,False,-1,NaN,NaN,False,9.209810e+05,False,NaN,False,NaN,3.882580e+05,3.882580e+05,0,False,False,ALUMINIUM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33144,C,A,20200101,2020,52,2020,792,TUR,TÃ¼rkiye,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,90395.0,False,8,kg,90395.0,False,9.039500e+04,False,0.0,False,0.0,1.611700e+05,1.611700e+05,0,False,True,ZIRCONIUM
33145,C,A,20200101,2020,52,2020,804,UKR,Ukraine,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,15980300.0,False,8,kg,15980300.0,False,1.598030e+07,False,0.0,False,0.0,2.064597e+07,2.064597e+07,0,False,True,ZIRCONIUM
33146,C,A,20200101,2020,52,2020,826,GBR,United Kingdom,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,1223196.0,False,8,kg,1223196.0,False,1.223196e+06,False,0.0,False,0.0,3.896642e+06,3.896642e+06,0,False,True,ZIRCONIUM
33147,C,A,20200101,2020,52,2020,834,TZA,United Rep. of Tanzania,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,765000.0,False,8,kg,765000.0,False,7.650000e+05,False,0.0,False,0.0,2.295000e+05,2.295000e+05,0,False,True,ZIRCONIUM
33148,C,A,20200101,2020,52,2020,842,USA,USA,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,20982638.0,False,8,kg,20982638.0,False,2.098264e+07,False,0.0,False,0.0,3.562715e+07,3.562715e+07,0,False,True,ZIRCONIUM

In [162]:
df_exports_summarized = df_exports.groupby(["Year", "Product"])[["netWgt"]].sum().reset_index()
df_exports_summarized.rename(columns={"netWgt": "Total_netWgt_YearProduct"}, inplace=True)
df_exports_summarized

     Year    Product  Total_netWgt_YearProduct
0    2000  ALUMINIUM              1.735930e+10
1    2000   ANTIMONY              6.013568e+06
2    2000   ASBESTOS              6.939951e+08
3    2000    BARYTES              3.441228e+09
4    2000    BISMUTH              1.172789e+07
..    ...        ...                       ...
653  2020   TITANIUM              4.017014e+09
654  2020   TUNGSTEN              1.234453e+07
655  2020    URANIUM              6.182528e+06
656  2020       ZINC              9.635898e+09
657  2020  ZIRCONIUM              5.196047e+08

[658 rows x 3 columns]

In [127]:
df_exports_summarized[df_exports_summarized["Product"] == 'RARE EARTH']

     Year     Product  Total_netWgt_YearProduct
22   2000  RARE EARTH              6.671754e+07
52   2001  RARE EARTH              6.598505e+07
83   2002  RARE EARTH              6.514740e+07
114  2003  RARE EARTH              8.488651e+07
145  2004  RARE EARTH              8.922660e+07
176  2005  RARE EARTH              8.204449e+07
207  2006  RARE EARTH              9.402620e+07
238  2007  RARE EARTH              8.481393e+07
269  2008  RARE EARTH              8.642741e+07
300  2009  RARE EARTH              7.007873e+07
331  2010  RARE EARTH              7.095524e+07
362  2011  RARE EARTH              5.193187e+07
394  2012  RARE EARTH              5.131700e+07
426  2013  RARE EARTH              5.905520e+07
458  2014  RARE EARTH              7.647683e+07
490  2015  RARE EARTH              8.662689e+07
522  2016  RARE EARTH              4.720952e+07
554  2017  RARE EARTH              1.051511e+08
586  2018  RARE EARTH              8.230182e+07
618  2019  RARE EARTH              1.309705e+08
650  2020  RARE EARTH              1.306390e+08

### Let's left-join production and total value of production by (Year, Product)

In [163]:
df_e = pd.merge(df_exports, df_exports_summarized, how="left", left_on=["Year", "Product"], right_on=["Year", "Product"])
df_e

,typeCode,freqCode,refPeriodId,refYear,refMonth,Year,reporterCode,reporterISO,reporterDesc,flowCode,flowDesc,partnerCode,partnerISO,partnerDesc,partner2Code,partner2ISO,partner2Desc,classificationCode,classificationSearchCode,isOriginalClassification,cmdCode,cmdDesc,aggrLevel,isLeaf,customsCode,customsDesc,mosCode,motCode,motDesc,qtyUnitCode,qtyUnitAbbr,qty,isQtyEstimated,altQtyUnitCode,altQtyUnitAbbr,altQty,isAltQtyEstimated,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate,Product,Total_netWgt_YearProduct
0,C,A,20000101,2000,52,2000,32,ARG,Argentina,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,14000.0,False,-1,NaN,NaN,False,1.400000e+04,False,NaN,False,NaN,4.291000e+03,4.291000e+03,0,False,False,ALUMINIUM,1.735930e+10
1,C,A,20000101,2000,52,2000,40,AUT,Austria,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,128800.0,False,-1,NaN,NaN,False,1.288000e+05,False,NaN,False,NaN,2.275000e+04,2.275000e+04,0,False,False,ALUMINIUM,1.735930e+10
2,C,A,20000101,2000,52,2000,56,BEL,Belgium,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,133826657.0,False,-1,NaN,NaN,False,1.338267e+08,False,NaN,False,NaN,1.435771e+07,1.435771e+07,0,False,False,ALUMINIUM,1.735930e+10
3,C,A,20000101,2000,52,2000,76,BRA,Brazil,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,5135286.0,False,8,kg,5135286.0,False,4.166202e+09,False,0.0,False,0.0,1.131292e+08,1.131292e+08,0,False,True,ALUMINIUM,1.735930e+10
4,C,A,20000101,2000,52,2000,100,BGR,Bulgaria,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,920981.0,False,-1,NaN,NaN,False,9.209810e+05,False,NaN,False,NaN,3.882580e+05,3.882580e+05,0,False,False,ALUMINIUM,1.735930e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33144,C,A,20200101,2020,52,2020,792,TUR,TÃ¼rkiye,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,90395.0,False,8,kg,90395.0,False,9.039500e+04,False,0.0,False,0.0,1.611700e+05,1.611700e+05,0,False,True,ZIRCONIUM,5.196047e+08
33145,C,A,20200101,2020,52,2020,804,UKR,Ukraine,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,15980300.0,False,8,kg,15980300.0,False,1.598030e+07,False,0.0,False,0.0,2.064597e+07,2.064597e+07,0,False,True,ZIRCONIUM,5.196047e+08
33146,C,A,20200101,2020,52,2020,826,GBR,United Kingdom,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,1223196.0,False,8,kg,1223196.0,False,1.223196e+06,False,0.0,False,0.0,3.896642e+06,3.896642e+06,0,False,True,ZIRCONIUM,5.196047e+08
33147,C,A,20200101,2020,52,2020,834,TZA,United Rep. of Tanzania,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,765000.0,False,8,kg,765000.0,False,7.650000e+05,False,0.0,False,0.0,2.295000e+05,2.295000e+05,0,False,True,ZIRCONIUM,5.196047e+08
33148,C,A,20200101,2020,52,2020,842,USA,USA,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,20982638.0,False,8,kg,20982638.0,False,2.098264e+07,False,0.0,False,0.0,3.562715e+07,3.562715e+07,0,False,True,ZIRCONIUM,5.196047e+08

In [164]:
# df_e["Share in %"] = df_e["netWgt"] * 100 / df_e["Total_netWgt_YearProduct"]
df_e["Share in %"] = df_e["netWgt"] * 1 / df_e["Total_netWgt_YearProduct"]
df_e["Share HHI Exports"] = df_e["Share in %"] ** 2
df_e

,typeCode,freqCode,refPeriodId,refYear,refMonth,Year,reporterCode,reporterISO,reporterDesc,flowCode,flowDesc,partnerCode,partnerISO,partnerDesc,partner2Code,partner2ISO,partner2Desc,classificationCode,classificationSearchCode,isOriginalClassification,cmdCode,cmdDesc,aggrLevel,isLeaf,customsCode,customsDesc,mosCode,motCode,motDesc,qtyUnitCode,qtyUnitAbbr,qty,isQtyEstimated,altQtyUnitCode,altQtyUnitAbbr,altQty,isAltQtyEstimated,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate,Product,Total_netWgt_YearProduct,Share in %,Share HHI Exports
0,C,A,20000101,2000,52,2000,32,ARG,Argentina,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,14000.0,False,-1,NaN,NaN,False,1.400000e+04,False,NaN,False,NaN,4.291000e+03,4.291000e+03,0,False,False,ALUMINIUM,1.735930e+10,8.064842e-07,6.504168e-13
1,C,A,20000101,2000,52,2000,40,AUT,Austria,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,128800.0,False,-1,NaN,NaN,False,1.288000e+05,False,NaN,False,NaN,2.275000e+04,2.275000e+04,0,False,False,ALUMINIUM,1.735930e+10,7.419655e-06,5.505128e-11
2,C,A,20000101,2000,52,2000,56,BEL,Belgium,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,133826657.0,False,-1,NaN,NaN,False,1.338267e+08,False,NaN,False,NaN,1.435771e+07,1.435771e+07,0,False,False,ALUMINIUM,1.735930e+10,7.709221e-03,5.943208e-05
3,C,A,20000101,2000,52,2000,76,BRA,Brazil,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,5135286.0,False,8,kg,5135286.0,False,4.166202e+09,False,0.0,False,0.0,1.131292e+08,1.131292e+08,0,False,True,ALUMINIUM,1.735930e+10,2.399983e-01,5.759918e-02
4,C,A,20000101,2000,52,2000,100,BGR,Bulgaria,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,920981.0,False,-1,NaN,NaN,False,9.209810e+05,False,NaN,False,NaN,3.882580e+05,3.882580e+05,0,False,False,ALUMINIUM,1.735930e+10,5.305405e-05,2.814732e-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33144,C,A,20200101,2020,52,2020,792,TUR,TÃ¼rkiye,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,90395.0,False,8,kg,90395.0,False,9.039500e+04,False,0.0,False,0.0,1.611700e+05,1.611700e+05,0,False,True,ZIRCONIUM,5.196047e+08,1.739688e-04,3.026514e-08
33145,C,A,20200101,2020,52,2020,804,UKR,Ukraine,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,15980300.0,False,8,kg,15980300.0,False,1.598030e+07,False,0.0,False,0.0,2.064597e+07,2.064597e+07,0,False,True,ZIRCONIUM,5.196047e+08,3.075473e-02,9.458533e-04
33146,C,A,20200101,2020,52,2020,826,GBR,United Kingdom,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,1223196.0,False,8,kg,1223196.0,False,1.223196e+06,False,0.0,False,0.0,3.896642e+06,3.896642e+06,0,False,True,ZIRCONIUM,5.196047e+08,2.354090e-03,5.541738e-06
33147,C,A,20200101,2020,52,2020,834,TZA,United Rep. of Tanzania,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,765000.0,False,8,kg,765000.0,False,7.650000e+05,False,0.0,False,0.0,2.295000e+05,2.295000e+05,0,False,True,ZIRCONIUM,5.196047e+08,1.472273e-03,2.167588e-06
33148,C,A,20200101,2020,52,2020,842,USA,USA,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,20982638.0,False,8,kg,20982638.0,False,2.098264e+07,False,0.0,False,0.0,3.562715e+07,3.562715e+07,0,False,True,ZIRCONIUM,5.196047e+08,4.038193e-02,1.630700e-03

### Sum the "Share HHI Exports" by (Year, Product) and you get the HHI index :)

In [165]:
df_hhi_exports = df_e.groupby(["Year", "Product"])[["Share HHI Exports"]].sum().reset_index()
df_hhi_exports.rename(columns={"Share HHI Exports": "HHI_exports"}, inplace=True)
df_hhi_exports = pd.merge(df_e, df_hhi_exports, how="left", left_on=["Year", "Product"], right_on=["Year", "Product"])
df_hhi_exports

# SAME: Currently the HHI value is pasted to the row even if the production is null. Shall we replace by NANs if production is null?

,typeCode,freqCode,refPeriodId,refYear,refMonth,Year,reporterCode,reporterISO,reporterDesc,flowCode,flowDesc,partnerCode,partnerISO,partnerDesc,partner2Code,partner2ISO,partner2Desc,classificationCode,classificationSearchCode,isOriginalClassification,cmdCode,cmdDesc,aggrLevel,isLeaf,customsCode,customsDesc,mosCode,motCode,motDesc,qtyUnitCode,qtyUnitAbbr,qty,isQtyEstimated,altQtyUnitCode,altQtyUnitAbbr,altQty,isAltQtyEstimated,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate,Product,Total_netWgt_YearProduct,Share in %,Share HHI Exports,HHI_exports
0,C,A,20000101,2000,52,2000,32,ARG,Argentina,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,14000.0,False,-1,NaN,NaN,False,1.400000e+04,False,NaN,False,NaN,4.291000e+03,4.291000e+03,0,False,False,ALUMINIUM,1.735930e+10,8.064842e-07,6.504168e-13,0.221975
1,C,A,20000101,2000,52,2000,40,AUT,Austria,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,128800.0,False,-1,NaN,NaN,False,1.288000e+05,False,NaN,False,NaN,2.275000e+04,2.275000e+04,0,False,False,ALUMINIUM,1.735930e+10,7.419655e-06,5.505128e-11,0.221975
2,C,A,20000101,2000,52,2000,56,BEL,Belgium,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,133826657.0,False,-1,NaN,NaN,False,1.338267e+08,False,NaN,False,NaN,1.435771e+07,1.435771e+07,0,False,False,ALUMINIUM,1.735930e+10,7.709221e-03,5.943208e-05,0.221975
3,C,A,20000101,2000,52,2000,76,BRA,Brazil,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,5135286.0,False,8,kg,5135286.0,False,4.166202e+09,False,0.0,False,0.0,1.131292e+08,1.131292e+08,0,False,True,ALUMINIUM,1.735930e+10,2.399983e-01,5.759918e-02,0.221975
4,C,A,20000101,2000,52,2000,100,BGR,Bulgaria,X,Export,0,W00,World,0,W00,World,H1,HS,True,2606,Aluminium ores and concentrates,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,920981.0,False,-1,NaN,NaN,False,9.209810e+05,False,NaN,False,NaN,3.882580e+05,3.882580e+05,0,False,False,ALUMINIUM,1.735930e+10,5.305405e-05,2.814732e-09,0.221975
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33144,C,A,20200101,2020,52,2020,792,TUR,TÃ¼rkiye,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,90395.0,False,8,kg,90395.0,False,9.039500e+04,False,0.0,False,0.0,1.611700e+05,1.611700e+05,0,False,True,ZIRCONIUM,5.196047e+08,1.739688e-04,3.026514e-08,0.121045
33145,C,A,20200101,2020,52,2020,804,UKR,Ukraine,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,15980300.0,False,8,kg,15980300.0,False,1.598030e+07,False,0.0,False,0.0,2.064597e+07,2.064597e+07,0,False,True,ZIRCONIUM,5.196047e+08,3.075473e-02,9.458533e-04,0.121045
33146,C,A,20200101,2020,52,2020,826,GBR,United Kingdom,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,1223196.0,False,8,kg,1223196.0,False,1.223196e+06,False,0.0,False,0.0,3.896642e+06,3.896642e+06,0,False,True,ZIRCONIUM,5.196047e+08,2.354090e-03,5.541738e-06,0.121045
33147,C,A,20200101,2020,52,2020,834,TZA,United Rep. of Tanzania,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,765000.0,False,8,kg,765000.0,False,7.650000e+05,False,0.0,False,0.0,2.295000e+05,2.295000e+05,0,False,True,ZIRCONIUM,5.196047e+08,1.472273e-03,2.167588e-06,0.121045
33148,C,A,20200101,2020,52,2020,842,USA,USA,X,Export,0,W00,World,0,W00,World,H5,HS,True,261510,Zirconium ores and concentrates,6,True,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,20982638.0,False,8,kg,20982638.0,False,2.098264e+07,False,0.0,False,0.0,3.562715e+07,3.562715e+07,0,False,True,ZIRCONIUM,5.196047e+08,4.038193e-02,1.630700e-03,0.121045

In [167]:
df_hhi_exports = df_hhi_exports[["Product", "cmdCode", "Year", "qtyUnitAbbr", "HHI_exports"]].drop_duplicates(subset=["Product", "cmdCode", "Year", "qtyUnitAbbr"]).reset_index(drop=True)
df_hhi_exports

       Product  cmdCode  Year qtyUnitAbbr  HHI_exports
0    ALUMINIUM     2606  2000          kg     0.221975
1    ALUMINIUM     2606  2000         NaN     0.221975
2     ANTIMONY   261710  2000          kg     0.243016
3     ASBESTOS     2524  2000          kg     0.303755
4      BARYTES     2511  2000          kg     0.550579
..         ...      ...   ...         ...          ...
666   TITANIUM     2614  2020          kg     0.146269
667   TUNGSTEN     2611  2020          kg     0.111200
668    URANIUM   261210  2020          kg     0.578258
669       ZINC     2608  2020          kg     0.107373
670  ZIRCONIUM   261510  2020          kg     0.121045

[671 rows x 5 columns]

In [98]:
df_hhi_exports[(df_hhi_exports["Year"] == 2000) & (df_hhi_exports["Product"] == 'NICKEL')]

   Product  cmdCode  Year  HHI_exports
20  NICKEL     2604  2000     0.352546

### Scale HHI between [0,1]

In [168]:
# max_value is 10,000 and is canada for selenium. It's the only one country that produces seleniun
max_hhi = df_hhi_exports["HHI_exports"].max()
min_hhi = df_hhi_exports["HHI_exports"].min()
df_hhi_exports["HHI_exports_scaled"] = (df_hhi_exports["HHI_exports"] - min_hhi) / (max_hhi - min_hhi)
df_hhi_exports

       Product  cmdCode  Year qtyUnitAbbr  HHI_exports  HHI_exports_scaled
0    ALUMINIUM     2606  2000          kg     0.221975            0.164204
1    ALUMINIUM     2606  2000         NaN     0.221975            0.164204
2     ANTIMONY   261710  2000          kg     0.243016            0.187429
3     ASBESTOS     2524  2000          kg     0.303755            0.254476
4      BARYTES     2511  2000          kg     0.550579            0.526929
..         ...      ...   ...         ...          ...                 ...
666   TITANIUM     2614  2020          kg     0.146269            0.080637
667   TUNGSTEN     2611  2020          kg     0.111200            0.041927
668    URANIUM   261210  2020          kg     0.578258            0.557482
669       ZINC     2608  2020          kg     0.107373            0.037702
670  ZIRCONIUM   261510  2020          kg     0.121045            0.052793

[671 rows x 6 columns]

In [133]:
df_hhi_exports[(df_hhi_exports["Year"] == 2000) & (df_hhi_exports["Product"] == 'RARE EARTH')]

       Product  cmdCode  Year qtyUnitAbbr  HHI_exports  HHI_exports_scaled
24  RARE EARTH     2846  2000          kg     0.720773            0.714794

In [169]:
df_hhi_exports.to_csv("../../data/hhi_data/df_hhi_exports.csv", index=False)

## Now join data from both HHI dataframes

In [170]:
pd.set_option('display.max_columns', None)

In [171]:
df_hhi_production = pd.read_csv("../../data/hhi_data/df_hhi_production_2000.csv")
df_hhi_exports = pd.read_csv("../../data/hhi_data/df_hhi_exports.csv")

In [172]:
# df_hhi_production.loc[df_hhi_production["reporterCode"].notnull(), 'reporterCode'] = df_hhi_production.loc[df_hhi_production['reporterCode'].notnull(), 'reporterCode'].apply(int).apply(str)
df_hhi_production.loc[df_hhi_production["cmdCode"].notnull(), 'cmdCode'] = df_hhi_production.loc[df_hhi_production['cmdCode'].notnull(), 'cmdCode'].apply(int).apply(str)
df_hhi_production.rename(columns={"Share in %": "Share in % (production)"}, inplace=True)
df_hhi_production

,Product,cmdCode,Year,qtyUnitAbbr,Source,HHI_production,HHI_production_scaled
0,IRON ORE (FE-CONT.),2601,2000,kg,org,0.120238,0.075656
1,IRON ORE (FE-CONT.),2601,2001,kg,org,0.127200,0.083260
2,IRON ORE (FE-CONT.),2601,2002,kg,org,0.124491,0.080301
3,IRON ORE (FE-CONT.),2601,2003,kg,org,0.127726,0.083835
4,IRON ORE (FE-CONT.),2601,2004,kg,org,0.132830,0.089409
...,...,...,...,...,...,...,...
1402,URANIUM (U3O8-CONT.),261210,2016,kg,org,0.224366,0.189390
1403,URANIUM (U3O8-CONT.),261210,2017,kg,org,0.219018,0.183548
1404,URANIUM (U3O8-CONT.),261210,2018,kg,org,0.212503,0.176431
1405,URANIUM (U3O8-CONT.),261210,2019,kg,org,0.227431,0.192737
1406,URANIUM (U3O8-CONT.),261210,2020,kg,org,0.218243,0.182702

In [138]:
df_hhi_production.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1407 entries, 0 to 1406
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Product                1407 non-null   object
 1   cmdCode                651 non-null    object
 2   Year                   1407 non-null   int64
 3   qtyUnitAbbr            1407 non-null   object
 4   HHI_production         1407 non-null   float64
 5   HHI_production_scaled  1407 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 66.1+ KB

In [173]:
# df_hhi_exports.loc[df_hhi_exports["reporterCode"].notnull(), 'reporterCode'] = df_hhi_exports.loc[df_hhi_exports['reporterCode'].notnull(), 'reporterCode'].apply(int).apply(str)
df_hhi_exports.loc[df_hhi_exports["cmdCode"].notnull(), 'cmdCode'] = df_hhi_exports.loc[df_hhi_exports['cmdCode'].notnull(), 'cmdCode'].apply(int).apply(str)
df_hhi_exports.rename(columns={"Share in %": "Share in % (exports)"}, inplace=True)
df_hhi_exports

       Product cmdCode  Year qtyUnitAbbr  HHI_exports  HHI_exports_scaled
0    ALUMINIUM    2606  2000          kg     0.221975            0.164204
1    ALUMINIUM    2606  2000         NaN     0.221975            0.164204
2     ANTIMONY  261710  2000          kg     0.243016            0.187429
3     ASBESTOS    2524  2000          kg     0.303755            0.254476
4      BARYTES    2511  2000          kg     0.550579            0.526929
..         ...     ...   ...         ...          ...                 ...
666   TITANIUM    2614  2020          kg     0.146269            0.080637
667   TUNGSTEN    2611  2020          kg     0.111200            0.041927
668    URANIUM  261210  2020          kg     0.578258            0.557482
669       ZINC    2608  2020          kg     0.107373            0.037702
670  ZIRCONIUM  261510  2020          kg     0.121045            0.052793

[671 rows x 6 columns]

In [174]:
df_hhi_exports.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 671 entries, 0 to 670
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Product             671 non-null    object
 1   cmdCode             671 non-null    object
 2   Year                671 non-null    int64
 3   qtyUnitAbbr         670 non-null    object
 4   HHI_exports         671 non-null    float64
 5   HHI_exports_scaled  671 non-null    float64
dtypes: float64(2), int64(1), object(3)
memory usage: 31.6+ KB

### Merge both dataframes

In [112]:
# df_hhi_exports["qtyUnitAbbr"].unique()

In [175]:
# df_hhi_master = pd.merge(df_hhi_production, df_hhi_exports, how="outer", left_on=["Year", "reporterCode", "cmdCode", "qtyUnitAbbr"], right_on=["Year", "reporterCode", "cmdCode", "qtyUnitAbbr"])
df_hhi_master = pd.merge(df_hhi_production, df_hhi_exports, how="outer", left_on=["Year", "cmdCode", "qtyUnitAbbr"], right_on=["Year", "cmdCode", "qtyUnitAbbr"])
df_hhi_master

,Product_x,cmdCode,Year,qtyUnitAbbr,Source,HHI_production,HHI_production_scaled,Product_y,HHI_exports,HHI_exports_scaled
0,IRON ORE (FE-CONT.),2601,2000,kg,org,0.120238,0.075656,IRON,0.383618,0.342631
1,IRON ORE (FE-CONT.),2601,2001,kg,org,0.127200,0.083260,IRON,0.336855,0.291013
2,IRON ORE (FE-CONT.),2601,2002,kg,org,0.124491,0.080301,IRON,0.271638,0.219024
3,IRON ORE (FE-CONT.),2601,2003,kg,org,0.127726,0.083835,IRON,0.289253,0.238467
4,IRON ORE (FE-CONT.),2601,2004,kg,org,0.132830,0.089409,IRON,0.301543,0.252034
...,...,...,...,...,...,...,...,...,...,...
1445,NaN,850760,2019,kg,NaN,NaN,NaN,LITHIUM-ION BATTERIES,0.265269,0.211994
1446,NaN,810411,2019,kg,NaN,NaN,NaN,MAGNESIUM,0.802419,0.804918
1447,NaN,850760,2020,u,NaN,NaN,NaN,LITHIUM-ION BATTERIES,0.352185,0.307934
1448,NaN,850760,2020,kg,NaN,NaN,NaN,LITHIUM-ION BATTERIES,0.352185,0.307934
1449,NaN,810411,2020,kg,NaN,NaN,NaN,MAGNESIUM,0.750842,0.747985

In [143]:
# Data that contains HHI production and Exports
df_hhi_master[~(df_hhi_master["HHI_exports"].isna()) & ~(df_hhi_master["HHI_production"].isna())]

,Product_x,cmdCode,Year,qtyUnitAbbr,HHI_production,HHI_production_scaled,Product_y,HHI_exports,HHI_exports_scaled
0,IRON ORE (FE-CONT.),2601,2000,kg,0.120238,0.075656,IRON,0.383618,0.342631
1,IRON ORE (FE-CONT.),2601,2001,kg,0.127200,0.083260,IRON,0.336855,0.291013
2,IRON ORE (FE-CONT.),2601,2002,kg,0.124491,0.080301,IRON,0.271638,0.219024
3,IRON ORE (FE-CONT.),2601,2003,kg,0.127726,0.083835,IRON,0.289253,0.238467
4,IRON ORE (FE-CONT.),2601,2004,kg,0.132830,0.089409,IRON,0.301543,0.252034
...,...,...,...,...,...,...,...,...,...
1402,URANIUM (U3O8-CONT.),261210,2016,kg,0.224366,0.189390,URANIUM,0.652551,0.639489
1403,URANIUM (U3O8-CONT.),261210,2017,kg,0.219018,0.183548,URANIUM,0.381732,0.340550
1404,URANIUM (U3O8-CONT.),261210,2018,kg,0.212503,0.176431,URANIUM,0.617763,0.601088
1405,URANIUM (U3O8-CONT.),261210,2019,kg,0.227431,0.192737,URANIUM,0.633501,0.618461
1406,URANIUM (U3O8-CONT.),261210,2020,kg,0.218243,0.182702,URANIUM,0.578258,0.557482

In [ ]:
df_hhi_exports[(df_hhi_exports["Year"]==2016) & (df_hhi_exports["reporterDesc"] == "China")] # ALUMINUM DOES NOT EXIST FOR CHINA,2016

In [192]:
df_hhi_exports[(df_hhi_exports["Year"]==2009) & (df_hhi_exports["reporterDesc"] == "Croatia")] # ALUMINUM DOES NOT EXIST FOR CROATIA,2009

,typeCode,freqCode,refPeriodId,refYear,refMonth,Year,reporterCode,reporterISO,reporterDesc,flowCode,...,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate,Product,Total_netWgt_YearProduct,Share in % (exports),Share HHI Exports,HHI_exports
13083,C,A,20090101,2009,52,2009,191,HRV,Croatia,X,...,9777.0,9777.0,0,True,False,BARYTES,3.581624e+09,1.423935e-04,2.027591e-08,3146.684482
13286,C,A,20090101,2009,52,2009,191,HRV,Croatia,X,...,10117.0,10117.0,0,True,False,COAL,9.556307e+11,5.347254e-08,2.859312e-15,1727.556377
13491,C,A,20090101,2009,52,2009,191,HRV,Croatia,X,...,3473804.0,3473804.0,0,True,False,GOLD,1.910489e+07,7.327965e-04,5.369907e-07,3611.730996
13600,C,A,20090101,2009,52,2009,191,HRV,Croatia,X,...,4581.0,4581.0,0,True,False,GRAPHITE,5.681944e+08,1.839159e-04,3.382506e-08,6551.476056
14087,C,A,20090101,2009,52,2009,191,HRV,Croatia,X,...,437505.0,437505.0,0,True,False,NATURAL GAS,1.302709e+11,5.712951e-04,3.263781e-07,1253.800340

In [ ]:
df_hhi_master[(df_hhi_master["Year"]==2016) & (df_hhi_master["Country"] == "CHINA")]

In [191]:
df_hhi_master[(df_hhi_master["Year"]==2009) & (df_hhi_master["Country"] == "CROATIA")]

,Year,Country,Value,Product,reporterCode,reporterDesc_x,Total_value_YearProduct,Share in % (production),Share HHI Production,HHI_production,...,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate,Total_netWgt_YearProduct,Share in % (exports),Share HHI Exports,HHI_exports
294,2009,CROATIA,500.0,ALUMINIUM,191,CROATIA,197735840.0,0.000253,6.393950e-08,1713.133234,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6720,2009,CROATIA,NaN,BARYTES,191,CROATIA,7662051.0,NaN,NaN,2359.851398,...,NaN,9777.0,9777.0,0.0,True,False,3.581624e+09,0.000142,2.027591e-08,3146.684482
47963,2009,CROATIA,NaN,SILVER,191,CROATIA,22322463.0,NaN,NaN,981.801726,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [176]:
df_hhi_master.to_csv("../../data/hhi_data/df_hhi_master.csv", index=False)

In [145]:
tt = pd.read_csv("../../data/hhi_data/df_hhi_master.csv")

In [146]:
tt[(tt["Product_y"] == "RARE EARTH")]

,Product_x,cmdCode,Year,qtyUnitAbbr,HHI_production,HHI_production_scaled,Product_y,HHI_exports,HHI_exports_scaled
1113,RARE EARTHS (REO-CONT.),2846.0,2000,kg,0.805740,0.824394,RARE EARTH,0.720773,0.714794
1114,RARE EARTHS (REO-CONT.),2846.0,2001,kg,0.810238,0.829307,RARE EARTH,0.628768,0.613236
1115,RARE EARTHS (REO-CONT.),2846.0,2002,kg,0.767105,0.782195,RARE EARTH,0.593503,0.574310
1116,RARE EARTHS (REO-CONT.),2846.0,2003,kg,0.796257,0.814037,RARE EARTH,0.545447,0.521264
1117,RARE EARTHS (REO-CONT.),2846.0,2004,kg,0.928109,0.958052,RARE EARTH,0.436989,0.401544
1118,RARE EARTHS (REO-CONT.),2846.0,2005,kg,0.932605,0.962962,RARE EARTH,0.428646,0.392335
1119,RARE EARTHS (REO-CONT.),2846.0,2006,kg,0.925519,0.955223,RARE EARTH,0.345647,0.300718
1120,RARE EARTHS (REO-CONT.),2846.0,2007,kg,0.932572,0.962927,RARE EARTH,0.286745,0.235700
1121,RARE EARTHS (REO-CONT.),2846.0,2008,kg,0.946979,0.978663,RARE EARTH,0.343328,0.298157
1122,RARE EARTHS (REO-CONT.),2846.0,2009,kg,0.966515,1.000000,RARE EARTH,0.339521,0.293955
1123,RARE EARTHS (REO-CONT.),2846.0,2010,kg,0.964405,0.997696,RARE EARTH,0.264772,0.211445
1124,RARE EARTHS (REO-CONT.),2846.0,2011,kg,0.915860,0.944673,RARE EARTH,0.120914,0.052649
1125,RARE EARTHS (REO-CONT.),2846.0,2012,kg,0.852536,0.875507,RARE EARTH,0.126589,0.058913
1126,RARE EARTHS (REO-CONT.),2846.0,2013,kg,0.867627,0.891990,RARE EARTH,0.160557,0.096408
1127,RARE EARTHS (REO-CONT.),2846.0,2014,kg,0.748603,0.761986,RARE EARTH,0.148771,0.083399
1128,RARE EARTHS (REO-CONT.),2846.0,2015,kg,0.726147,0.737459,RARE EARTH,0.168628,0.105318
1129,RARE EARTHS (REO-CONT.),2846.0,2016,kg,0.667193,0.673067,RARE EARTH,0.179062,0.116835
1130,RARE EARTHS (REO-CONT.),2846.0,2017,kg,0.639932,0.643290,RARE EARTH,0.253399,0.198891
1131,RARE EARTHS (REO-CONT.),2846.0,2018,kg,0.473936,0.461982,RARE EARTH,0.270307,0.217554
1132,RARE EARTHS (REO-CONT.),2846.0,2019,kg,0.468980,0.456568,RARE EARTH,0.250908,0.196141
1133,RARE EARTHS (REO-CONT.),2846.0,2020,kg,0.432554,0.416783,RARE EARTH,0.288779,0.237945